controllers:
  resource: ../src/Controller/
  type: attribute

admin_app_add:
  path: /admin/ajout-produit
  controller: App\Controller\AdminController::add

app_home:
  path: /
  controller: App\Controller\HomeController::home

admin_app_update:
  path: /admin/update-produit/{id}
  controller: App\Controller\AdminController::update
  requirements:
    id: '\d+'

admin_app_all:
  path: /admin/gestion-produits
  controller: App\Controller\AdminController::allProduits

admin_app_delete:
  path: /admin/delete-produit/{id}
  controller: App\Controller\AdminController::delete
  requirements:
    id: '\d+'

admin_app_select:
  path: /admin/select-produit/{id}
  controller: App\Controller\ProduitController::select
  requirements:
    id: '\d+'

app_allProduits:
  path: /produits
  controller: App\Controller\ProduitController::allProduits

admin_app_addCategorie:
  path: /admin/ajout-categorie
  controller: App\Controller\AdminController::addCategorie

app_select_categorie:
  path: /select-categorie/{id}
  controller: App\Controller\ProduitController::categorieProduits
  requirements:
    id: '\d+'

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_be_admin:
  path: /passer_admin/{id}
  controller: App\Controller\SecurityController::passerAdmin
  requirements:
    id: '\d+'
